name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      # Publish to npm when release is created
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Configure Git for authenticated access
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config --global url."https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}

      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - run: npm run build
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}

      # Publish to MCP Registry when release is created
      - name: Install MCP Publisher
        if: ${{ steps.release.outputs.release_created }}
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/latest/download/mcp-publisher_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" | tar xz mcp-publisher
      - name: Authenticate with domain
        if: ${{ steps.release.outputs.release_created }}
        env:
          MCP_PRIVATE_KEY: ${{ secrets.MCP_PRIVATE_KEY }}
        run: |
          ./mcp-publisher login http --domain hove.capital --private-key "$MCP_PRIVATE_KEY"

      - name: Publish to MCP Registry
        if: ${{ steps.release.outputs.release_created }}
        run: ./mcp-publisher publish
